steps:
  - id: terraform-apply
    name: hashicorp/terraform:1.0.7
    dir: './iaac/admin'
    args:
      - 'destroy'
      - '-auto-approve'
      - '-no-color'
      - '-input=false'

options:
  logging: CLOUD_LOGGING_ONLY