steps:
  - id: copy-sources
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./iaac/admin/bin/upload_artifacts.sh']

  - id: terraform-init
    name: hashicorp/terraform:1.0.7
    dir: './iaac/admin'
    args:
      - 'init'
      - '-no-color'
      - '-input=false'

  - id: terraform-plan
    name: hashicorp/terraform:1.0.7
    dir: './iaac/admin'
    args:
      - 'plan'
      - '-no-color'
      - '-input=false'

  - id: terraform-apply
    name: hashicorp/terraform:1.0.7
    dir: './iaac/admin'
    args:
      - 'apply'
      - '-auto-approve'
      - '-no-color'
      - '-input=false'

options:
  logging: CLOUD_LOGGING_ONLY