steps:
#  - id: 'Enable APIs'
#    name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: 'sh'
#    args:
#      - '-c'
#      - gcloud services enable container.googleapis.com
#
  - id: terraform-init
    name: hashicorp/terraform:1.0.7
    args:
      - 'init'
      - '-no-color'
      - '-input=false'
      - './iaac/admin'

  - id: terraform-plan
    name: hashicorp/terraform:1.0.7
    args:
      - 'plan'
      - '-no-color'
      - '-input=false'
      - './iaac/admin'

  - id: terraform-apply
    name: hashicorp/terraform:1.0.7
    args:
      - 'apply'
      - '-auto-approve'
      - '-no-color'
      - '-input=false'
      - './iaac/admin'


options:
  logging: CLOUD_LOGGING_ONLY