steps:
  - id: terraform-init
    name: hashicorp/terraform:1.0.7
    dir: './iaac/project2'
    args:
      - 'init'
      - '-no-color'
      - '-input=false'

  - id: terraform-plan
    name: hashicorp/terraform:1.0.7
    dir: './iaac/project2'
    args:
      - 'plan'
      - '-no-color'
      - '-input=false'

  - id: terraform-apply
    name: hashicorp/terraform:1.0.7
    dir: './iaac/project2'
    args:
      - 'apply'
      - '-auto-approve'
      - '-no-color'
      - '-input=false'

options:
  logging: CLOUD_LOGGING_ONLY