steps:
#  - id: 'Enable APIs'
#    name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: 'sh'
#    args:
#      - '-c'
#      - gcloud services enable container.googleapis.com
#
  - id: terraform-init
    name: hashicorp/terraform:0.14.8
    args:
      - 'init'
      - '-no-color'
      - '-input=false'
      - './gcp'

  - id: terraform-plan
    name: hashicorp/terraform:0.14.8
    args:
      - 'plan'
      - '-no-color'
      - '-input=false'
      - './gcp'

  - id: terraform-apply
    name: hashicorp/terraform:0.14.8
    args:
      - 'apply'
      - '-auto-approve'
      - '-no-color'
      - '-input=false'
      - './gcp'

  - id: build-image
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ['spring-boot:build-image']

  - id: push image
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ag-learn-gcp/hello-world-app']

options:
  logging: CLOUD_LOGGING_ONLY